"""Initial migration

Revision ID: 12df8546406a
Revises: 
Create Date: 2026-02-26 21:16:50.636395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12df8546406a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_languages_id'), 'languages', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('daily_card_target', sa.Integer(), nullable=False),
    sa.Column('daily_new_target', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'HIDDEN', name='deckstatus'), nullable=False),
    sa.Column('shared_code', sa.String(), nullable=True),
    sa.Column('deck_type', sa.String(), nullable=False),
    sa.Column('source_language_id', sa.Integer(), nullable=False),
    sa.Column('target_language_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['target_language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shared_code')
    )
    op.create_index(op.f('ix_decks_deck_type'), 'decks', ['deck_type'], unique=False)
    op.create_index(op.f('ix_decks_id'), 'decks', ['id'], unique=False)
    op.create_index(op.f('ix_decks_owner_id'), 'decks', ['owner_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_index('ix_refresh_tokens_user_revoked', 'refresh_tokens', ['user_id', 'revoked_at'], unique=False)
    op.create_table('user_learning_pairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_language_id', sa.Integer(), nullable=False),
    sa.Column('target_language_id', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['target_language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source_language_id', 'target_language_id', name='uq_user_learning_pairs_user_src_tgt')
    )
    op.create_index(op.f('ix_user_learning_pairs_id'), 'user_learning_pairs', ['id'], unique=False)
    op.create_index('ix_user_learning_pairs_user_default', 'user_learning_pairs', ['user_id', 'is_default'], unique=False)
    op.create_index(op.f('ix_user_learning_pairs_user_id'), 'user_learning_pairs', ['user_id'], unique=False)
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('front', sa.String(), nullable=False),
    sa.Column('front_norm', sa.String(), nullable=False),
    sa.Column('back', sa.String(), nullable=False),
    sa.Column('example_sentence', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deck_id', 'front_norm', name='uq_cards_deck_front_norm')
    )
    op.create_index(op.f('ix_cards_created_at'), 'cards', ['created_at'], unique=False)
    op.create_index(op.f('ix_cards_deck_id'), 'cards', ['deck_id'], unique=False)
    op.create_index(op.f('ix_cards_front_norm'), 'cards', ['front_norm'], unique=False)
    op.create_index(op.f('ix_cards_id'), 'cards', ['id'], unique=False)
    op.create_table('daily_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('learning_pair_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('cards_done', sa.Integer(), nullable=True),
    sa.Column('reviews_done', sa.Integer(), nullable=True),
    sa.Column('new_done', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['learning_pair_id'], ['user_learning_pairs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'learning_pair_id', 'date', name='uq_daily_progress_user_pair_date')
    )
    op.create_index(op.f('ix_daily_progress_date'), 'daily_progress', ['date'], unique=False)
    op.create_index(op.f('ix_daily_progress_learning_pair_id'), 'daily_progress', ['learning_pair_id'], unique=False)
    op.create_index(op.f('ix_daily_progress_user_id'), 'daily_progress', ['user_id'], unique=False)
    op.create_index('ix_daily_progress_user_pair_date', 'daily_progress', ['user_id', 'learning_pair_id', 'date'], unique=False)
    op.create_table('deck_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'EDITOR', 'VIEWER', name='deckrole'), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deck_id', 'user_id', name='uq_deck_access_deck_user')
    )
    op.create_index(op.f('ix_deck_access_deck_id'), 'deck_access', ['deck_id'], unique=False)
    op.create_index(op.f('ix_deck_access_user_id'), 'deck_access', ['user_id'], unique=False)
    op.create_table('user_card_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('times_seen', sa.Integer(), nullable=True),
    sa.Column('times_correct', sa.Integer(), nullable=True),
    sa.Column('last_review', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'card_id', name='uq_user_card_progress_user_card')
    )
    op.create_index(op.f('ix_user_card_progress_card_id'), 'user_card_progress', ['card_id'], unique=False)
    op.create_index(op.f('ix_user_card_progress_due_at'), 'user_card_progress', ['due_at'], unique=False)
    op.create_index(op.f('ix_user_card_progress_id'), 'user_card_progress', ['id'], unique=False)
    op.create_index('ix_user_card_progress_user_due_at', 'user_card_progress', ['user_id', 'due_at'], unique=False)
    op.create_index(op.f('ix_user_card_progress_user_id'), 'user_card_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_card_progress_user_id'), table_name='user_card_progress')
    op.drop_index('ix_user_card_progress_user_due_at', table_name='user_card_progress')
    op.drop_index(op.f('ix_user_card_progress_id'), table_name='user_card_progress')
    op.drop_index(op.f('ix_user_card_progress_due_at'), table_name='user_card_progress')
    op.drop_index(op.f('ix_user_card_progress_card_id'), table_name='user_card_progress')
    op.drop_table('user_card_progress')
    op.drop_index(op.f('ix_deck_access_user_id'), table_name='deck_access')
    op.drop_index(op.f('ix_deck_access_deck_id'), table_name='deck_access')
    op.drop_table('deck_access')
    op.drop_index('ix_daily_progress_user_pair_date', table_name='daily_progress')
    op.drop_index(op.f('ix_daily_progress_user_id'), table_name='daily_progress')
    op.drop_index(op.f('ix_daily_progress_learning_pair_id'), table_name='daily_progress')
    op.drop_index(op.f('ix_daily_progress_date'), table_name='daily_progress')
    op.drop_table('daily_progress')
    op.drop_index(op.f('ix_cards_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_front_norm'), table_name='cards')
    op.drop_index(op.f('ix_cards_deck_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_created_at'), table_name='cards')
    op.drop_table('cards')
    op.drop_index(op.f('ix_user_learning_pairs_user_id'), table_name='user_learning_pairs')
    op.drop_index('ix_user_learning_pairs_user_default', table_name='user_learning_pairs')
    op.drop_index(op.f('ix_user_learning_pairs_id'), table_name='user_learning_pairs')
    op.drop_table('user_learning_pairs')
    op.drop_index('ix_refresh_tokens_user_revoked', table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_decks_owner_id'), table_name='decks')
    op.drop_index(op.f('ix_decks_id'), table_name='decks')
    op.drop_index(op.f('ix_decks_deck_type'), table_name='decks')
    op.drop_table('decks')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_languages_id'), table_name='languages')
    op.drop_table('languages')
    # ### end Alembic commands ###
