"""Initial migration

Revision ID: 1a3c38f915a9
Revises: 
Create Date: 2026-02-23 13:19:48.273905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a3c38f915a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_languages_id'), 'languages', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('daily_card_target', sa.Integer(), nullable=False),
    sa.Column('daily_new_target', sa.Integer(), nullable=False),
    sa.Column('default_source_language_id', sa.Integer(), nullable=True),
    sa.Column('default_target_language_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['default_source_language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['default_target_language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('daily_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('cards_done', sa.Integer(), nullable=True),
    sa.Column('reviews_done', sa.Integer(), nullable=True),
    sa.Column('new_done', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_daily_progress_user_date')
    )
    op.create_index(op.f('ix_daily_progress_date'), 'daily_progress', ['date'], unique=False)
    op.create_index(op.f('ix_daily_progress_user_id'), 'daily_progress', ['user_id'], unique=False)
    op.create_table('decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'HIDDEN', name='deckstatus'), nullable=False),
    sa.Column('shared_code', sa.String(), nullable=True),
    sa.Column('source_language_id', sa.Integer(), nullable=False),
    sa.Column('target_language_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['target_language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shared_code')
    )
    op.create_index(op.f('ix_decks_id'), 'decks', ['id'], unique=False)
    op.create_index(op.f('ix_decks_owner_id'), 'decks', ['owner_id'], unique=False)
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('front', sa.String(), nullable=False),
    sa.Column('front_norm', sa.String(), nullable=False),
    sa.Column('back', sa.String(), nullable=False),
    sa.Column('example_sentence', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deck_id', 'front_norm', name='uq_cards_deck_front_norm')
    )
    op.create_index(op.f('ix_cards_created_at'), 'cards', ['created_at'], unique=False)
    op.create_index(op.f('ix_cards_deck_id'), 'cards', ['deck_id'], unique=False)
    op.create_index(op.f('ix_cards_front_norm'), 'cards', ['front_norm'], unique=False)
    op.create_index(op.f('ix_cards_id'), 'cards', ['id'], unique=False)
    op.create_table('deck_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'EDITOR', 'VIEWER', name='deckrole'), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deck_id', 'user_id', name='uq_deck_access_deck_user')
    )
    op.create_index(op.f('ix_deck_access_deck_id'), 'deck_access', ['deck_id'], unique=False)
    op.create_index(op.f('ix_deck_access_user_id'), 'deck_access', ['user_id'], unique=False)
    op.create_table('user_card_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('times_seen', sa.Integer(), nullable=True),
    sa.Column('times_correct', sa.Integer(), nullable=True),
    sa.Column('last_review', sa.DateTime(), nullable=True),
    sa.Column('stage', sa.Integer(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'card_id', name='uq_user_card_progress_user_card')
    )
    op.create_index(op.f('ix_user_card_progress_card_id'), 'user_card_progress', ['card_id'], unique=False)
    op.create_index(op.f('ix_user_card_progress_due_at'), 'user_card_progress', ['due_at'], unique=False)
    op.create_index(op.f('ix_user_card_progress_id'), 'user_card_progress', ['id'], unique=False)
    op.create_index('ix_user_card_progress_user_due_at', 'user_card_progress', ['user_id', 'due_at'], unique=False)
    op.create_index(op.f('ix_user_card_progress_user_id'), 'user_card_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_card_progress_user_id'), table_name='user_card_progress')
    op.drop_index('ix_user_card_progress_user_due_at', table_name='user_card_progress')
    op.drop_index(op.f('ix_user_card_progress_id'), table_name='user_card_progress')
    op.drop_index(op.f('ix_user_card_progress_due_at'), table_name='user_card_progress')
    op.drop_index(op.f('ix_user_card_progress_card_id'), table_name='user_card_progress')
    op.drop_table('user_card_progress')
    op.drop_index(op.f('ix_deck_access_user_id'), table_name='deck_access')
    op.drop_index(op.f('ix_deck_access_deck_id'), table_name='deck_access')
    op.drop_table('deck_access')
    op.drop_index(op.f('ix_cards_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_front_norm'), table_name='cards')
    op.drop_index(op.f('ix_cards_deck_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_created_at'), table_name='cards')
    op.drop_table('cards')
    op.drop_index(op.f('ix_decks_owner_id'), table_name='decks')
    op.drop_index(op.f('ix_decks_id'), table_name='decks')
    op.drop_table('decks')
    op.drop_index(op.f('ix_daily_progress_user_id'), table_name='daily_progress')
    op.drop_index(op.f('ix_daily_progress_date'), table_name='daily_progress')
    op.drop_table('daily_progress')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_languages_id'), table_name='languages')
    op.drop_table('languages')
    # ### end Alembic commands ###
